sort – B-spline Basis Function Library
sort Function
13 statements
Source File
private pure recursive function sort(x) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
Input array
Return Value real(kind=wp), dimension(size(x))
Calls
Called by
Contents
Source Code
sort
Source Code
        pure recursive function sort(x) result(res)
            real(wp), dimension(:), intent(in) :: x !< Input array
            real(wp), dimension(size(x)) :: res
            real(wp), dimension(size(x)-1) :: rest
            real(wp) :: pivot
            if(size(x) > 1)then
                pivot = head(split(x, 2))
                rest = [split(x, 1), tail(split(x, 2))]
                res = [sort(pack(rest, rest < pivot)), pivot, &
                        sort(pack(rest, rest >= pivot))]
            else
                res = x
            endif
        end function sort
Call graph
sort calls sort, split, head, tail
grevilleabscissae calls sort